name: Build

on: [push]

jobs:
  build_wheel_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install project dependencies
        run: poetry install

      - name: Build wheel package
        run: poetry build --format wheel

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-directory
          path: dist/
          
          
          
          
          
          
